using Telemachus.Business.Models;
using Telemachus.Data.Models;

namespace Telemachus.Business.Services.Mappers
{
    public static class MrvMisMapper
    {
        public static MrvMisBusinessModel ToBusinessModel(this MrvMisDataModel model)
        {
            if (model == null)
            {
                return null;
            }

            return new MrvMisBusinessModel()
            {
                Id = model.Id,
                Vessel = model.Vessel,
                Voyage = model.Voyage,
                EventId = model.EventId,
                EventTimestamp = model.EventTimestamp,
                StatusId = model.StatusId,
                EventName = model.EventName,
                ConditionName = model.ConditionName,
                CargoStatus = model.CargoStatus,
                PortName = model.PortName,
                ReportId = model.ReportId,
                InstructedSpeed = model.InstructedSpeed,
                InstructedChartererConsumption = model.InstructedChartererConsumption,
                RobHfoActual = model.RobHfoActual,
                RobHfoPool = model.RobHfoPool,
                RobMgoActual = model.RobMgoActual,
                RobMgoPool = model.RobMgoPool,
                DistanceToGo = model.DistanceToGo,
                DistanceOverGround = model.DistanceOverGround,
                SteamingTime = model.SteamingTime,
                VlsfoActualConsumptionMe = model.VlsfoActualConsumptionMe,
                VlsfoPoolConsumptionMe = model.VlsfoPoolConsumptionMe,
                LsmgoActualConsumptionMe = model.LsmgoActualConsumptionMe,
                LsmgoPoolConsumptionMe = model.LsmgoPoolConsumptionMe,
                WindForceForecast = model.WindForceForecast,
                Oop = model.Oop,
                AirCoolerCoolingWaterInletTemp = model.AirCoolerCoolingWaterInletTemp,
                AuxBlowerStatus = model.AuxBlowerStatus,
                BarometricPressure = model.BarometricPressure,
                Bdn = model.Bdn,
                BilgeRob = model.BilgeRob,
                Commingling = model.Commingling,
                CylinderOil = model.CylinderOil,
                DgOil = model.DgOil,
                Density = model.Density,
                Dg1Load = model.Dg1Load,
                Dg2Load = model.Dg2Load,
                Dg3Load = model.Dg3Load,
                Dg4Load = model.Dg4Load,
                DistilledWater = model.DistilledWater,
                DraftAft = model.DraftAft,
                DraftFwd = model.DraftFwd,
                ErTemp = model.ErTemp,
                EgeSteamPress = model.EgeSteamPress,
                ExhaustGasTempAfterTc = model.ExhaustGasTempAfterTc,
                ExhaustGasTempBeforeTc = model.ExhaustGasTempBeforeTc,
                ForecastWeather = model.ForecastWeather,
                FreshWaterDomestic = model.FreshWaterDomestic,
                FreshWaterPotable = model.FreshWaterPotable,
                FreshWaterTankCleaning = model.FreshWaterTankCleaning,
                FuelOilPumpIndex = model.FuelOilPumpIndex,
                FwProduction = model.FwProduction,
                Gsv = model.Gsv,
                KinematicViscosity = model.KinematicViscosity,
                LowerCalorifer = model.LowerCalorifer,
                LsmgoActualConsumptionBoiler1 = model.LsmgoActualConsumptionBoiler1,
                LsmgoActualConsumptionBoiler2 = model.LsmgoActualConsumptionBoiler2,
                LsmgoActualConsumptionCompositeBoiler = model.LsmgoActualConsumptionCompositeBoiler,
                LsmgoActualConsumptionCummins = model.LsmgoActualConsumptionCummins,
                LsmgoActualConsumptionDg1 = model.LsmgoActualConsumptionDg1,
                LsmgoActualConsumptionDg2 = model.LsmgoActualConsumptionDg2,
                LsmgoActualConsumptionDg3 = model.LsmgoActualConsumptionDg3,
                LsmgoActualConsumptionDg4 = model.LsmgoActualConsumptionDg4,
                LsmgoActualConsumptionIgg = model.LsmgoActualConsumptionIgg,
                LsmgoPoolConsumptionBoiler1 = model.LsmgoPoolConsumptionBoiler1,
                LsmgoPoolConsumptionBoiler2 = model.LsmgoPoolConsumptionBoiler2,
                LsmgoPoolConsumptionCompositeBoiler = model.LsmgoPoolConsumptionCompositeBoiler,
                LsmgoPoolConsumptionCummins = model.LsmgoPoolConsumptionCummins,
                LsmgoPoolConsumptionDg1 = model.LsmgoPoolConsumptionDg1,
                LsmgoPoolConsumptionDg2 = model.LsmgoPoolConsumptionDg2,
                LsmgoPoolConsumptionDg3 = model.LsmgoPoolConsumptionDg3,
                LsmgoPoolConsumptionDg4 = model.LsmgoPoolConsumptionDg4,
                LsmgoPoolConsumptionIgg = model.LsmgoPoolConsumptionIgg,
                MeOilOil = model.MeOilOil,
                MainEngineRevolutionOutputCounter = model.MainEngineRevolutionOutputCounter,
                ObservedWeather = model.ObservedWeather,
                RpmDeclared = model.RpmDeclared,
                RunningHoursBoiler1Lsmgo = model.RunningHoursBoiler1Lsmgo,
                RunningHoursBoiler1Vlsfo = model.RunningHoursBoiler1Vlsfo,
                RunningHoursBoiler2Lsmgo = model.RunningHoursBoiler2Lsmgo,
                RunningHoursBoiler2Vlsfo = model.RunningHoursBoiler2Vlsfo,
                RunningHoursCargoCumminsLsmgo = model.RunningHoursCargoCumminsLsmgo,
                RunningHoursCompositeBoilerLsmgo = model.RunningHoursCompositeBoilerLsmgo,
                RunningHoursCompositeBoilerVlsfo = model.RunningHoursCompositeBoilerVlsfo,
                RunningHoursDg1Lsmgo = model.RunningHoursDg1Lsmgo,
                RunningHoursDg1Vlsfo = model.RunningHoursDg1Vlsfo,
                RunningHoursDg2Lsmgo = model.RunningHoursDg2Lsmgo,
                RunningHoursDg2Vlsfo = model.RunningHoursDg2Vlsfo,
                RunningHoursDg3Lsmgo = model.RunningHoursDg3Lsmgo,
                RunningHoursDg3Vlsfo = model.RunningHoursDg3Vlsfo,
                RunningHoursDg4Lsmgo = model.RunningHoursDg4Lsmgo,
                RunningHoursDg4Vlsfo = model.RunningHoursDg4Vlsfo,
                RunningHoursIggLsmgoRunningHours = model.RunningHoursIggLsmgoRunningHours,
                ScavengeAirInletTemp = model.ScavengeAirInletTemp,
                ScavengeAirPressure = model.ScavengeAirPressure,
                SeaCurrentSpeed = model.SeaCurrentSpeed,
                SeaState = model.SeaState,
                ShaftPowerShapoli = model.ShaftPowerShapoli,
                SlipDeclared = model.SlipDeclared,
                Slops = model.Slops,
                SludgeRob = model.SludgeRob,
                Sounding = model.Sounding,
                SpeedlogDistance = model.SpeedlogDistance,
                SulphurContent = model.SulphurContent,
                SwellDirection = model.SwellDirection,
                TcAirInletTemp = model.TcAirInletTemp,
                TankTemperature = model.TankTemperature,
                TurboChargerRpm = model.TurboChargerRpm,
                Vcf = model.Vcf,
                VesselCurrentList = model.VesselCurrentList,
                VesselCurrentTrim = model.VesselCurrentTrim,
                VlsfoActualConsumptionBoiler1 = model.VlsfoActualConsumptionBoiler1,
                VlsfoActualConsumptionBoiler2 = model.VlsfoActualConsumptionBoiler2,
                VlsfoActualConsumptionCompositeBoiler = model.VlsfoActualConsumptionCompositeBoiler,
                VlsfoActualConsumptionDg1 = model.VlsfoActualConsumptionDg1,
                VlsfoActualConsumptionDg2 = model.VlsfoActualConsumptionDg2,
                VlsfoActualConsumptionDg3 = model.VlsfoActualConsumptionDg3,
                VlsfoActualConsumptionDg4 = model.VlsfoActualConsumptionDg4,
                VlsfoPoolConsumptionBoiler1 = model.VlsfoPoolConsumptionBoiler1,
                VlsfoPoolConsumptionBoiler2 = model.VlsfoPoolConsumptionBoiler2,
                VlsfoPoolConsumptionCompositeBoiler = model.VlsfoPoolConsumptionCompositeBoiler,
                VlsfoPoolConsumptionDg1 = model.VlsfoPoolConsumptionDg1,
                VlsfoPoolConsumptionDg2 = model.VlsfoPoolConsumptionDg2,
                VlsfoPoolConsumptionDg3 = model.VlsfoPoolConsumptionDg3,
                VlsfoPoolConsumptionDg4 = model.VlsfoPoolConsumptionDg4,
                Volume = model.Volume,
                Wcf = model.Wcf,
                Weight = model.Weight,
                WindDirection = model.WindDirection,
                WindForce = model.WindForce,
                Cargo = model.Cargo,
                PortBusinessId = model.PortBusinessId,
                AverageSpeedThroughTheWater = model.AverageSpeedThroughTheWater,
                AverageSpeedOverGround = model.AverageSpeedOverGround,
                TotalConsumptionEstimated = model.TotalConsumptionEstimated,
                TotalConsumptionDeclared = model.TotalConsumptionDeclared,
                VlsfoActualConsumptionThroughFlowMetersDiff = model.VlsfoActualConsumptionThroughFlowMetersDiff,
                VlsfoPoolConsumptionThroughFlowMetersDiff = model.VlsfoPoolConsumptionThroughFlowMetersDiff,
                LsmgoActualConsumptionThroughFlowMetersDiff = model.LsmgoActualConsumptionThroughFlowMetersDiff,
                LsmgoPoolConsumptionThroughFlowMetersDiff = model.LsmgoPoolConsumptionThroughFlowMetersDiff,
                MainEngineMaxPower = model.MainEngineMaxPower,
                PitchPropeller = model.PitchPropeller,
                TotalDistanceOverGround = model.TotalDistanceOverGround,
                ActualConsVlsfo = model.ActualConsVlsfo,
                ActualConsLsmgo = model.ActualConsLsmgo,
                PoolConsVlsfo = model.PoolConsVlsfo,
                PoolConsLsmgo = model.PoolConsLsmgo,
                EventTimestampUtc = model.EventTimestampUtc,
                Lat = model.Lat,
                Long = model.Long,
                BunkeringLsmgo = model.BunkeringLsmgo,
                IsEu = model.IsEu,
                RobLfoActual = model.RobLfoActual,
                RobLfoPool = model.RobLfoPool,
                BunkeringLfo = model.BunkeringLfo,
                BunkeringHfo = model.BunkeringHfo,
                LegId = model.LegId,
                RobHfoActualTanks = model.RobHfoActualTanks,
                RobHfoPoolTanks = model.RobHfoPoolTanks,
                RobMgoActualTanks = model.RobMgoActualTanks,
                RobMgoPoolTanks = model.RobMgoPoolTanks,
                PortNameFutureIfOpl = model.PortNameFutureIfOpl,
                PortBusinessIdFutureIfOpl = model.PortBusinessIdFutureIfOpl,
                IsEuFutureIfOpl = model.IsEuFutureIfOpl,
                PortNamePastIfOpl = model.PortNamePastIfOpl,
                PortBusinessIdPastIfOpl = model.PortBusinessIdPastIfOpl,
                IsEuPastIfOpl = model.IsEuPastIfOpl,
            };
        }
    }

}
