namespace Telemachus.Business.Models
{
    using System;

    public class MrvMisBusinessModel
    {
        public int Id { get; set; }
        public string Vessel { get; set; }
        public string Voyage { get; set; }
        public int? EventId { get; set; }
        public DateTime? EventTimestamp { get; set; }
        public int? StatusId { get; set; }
        public string EventName { get; set; }
        public string ConditionName { get; set; }
        public int? CargoStatus { get; set; }
        public string PortName { get; set; }
        public int? ReportId { get; set; }
        public string InstructedSpeed { get; set; }
        public string InstructedChartererConsumption { get; set; }
        public double? RobHfoActual { get; set; }
        public double? RobHfoPool { get; set; }
        public double? RobMgoActual { get; set; }
        public double? RobMgoPool { get; set; }
        public string DistanceToGo { get; set; }
        public string DistanceOverGround { get; set; }
        public string SteamingTime { get; set; }
        public string VlsfoActualConsumptionMe { get; set; }
        public string VlsfoPoolConsumptionMe { get; set; }
        public string LsmgoActualConsumptionMe { get; set; }
        public string LsmgoPoolConsumptionMe { get; set; }
        public string WindForceForecast { get; set; }
        public string Oop { get; set; }
        public string AirCoolerCoolingWaterInletTemp { get; set; }
        public string AuxBlowerStatus { get; set; }
        public string BarometricPressure { get; set; }
        public string Bdn { get; set; }
        public string BilgeRob { get; set; }
        public string Commingling { get; set; }
        public string CylinderOil { get; set; }
        public string DgOil { get; set; }
        public string Density { get; set; }
        public string Dg1Load { get; set; }
        public string Dg2Load { get; set; }
        public string Dg3Load { get; set; }
        public string Dg4Load { get; set; }
        public string DistilledWater { get; set; }
        public string DraftAft { get; set; }
        public string DraftFwd { get; set; }
        public string ErTemp { get; set; }
        public string EgeSteamPress { get; set; }
        public string ExhaustGasTempAfterTc { get; set; }
        public string ExhaustGasTempBeforeTc { get; set; }
        public string ForecastWeather { get; set; }
        public string FreshWaterDomestic { get; set; }
        public string FreshWaterPotable { get; set; }
        public string FreshWaterTankCleaning { get; set; }
        public string FuelOilPumpIndex { get; set; }
        public string FwProduction { get; set; }
        public string Gsv { get; set; }
        public string KinematicViscosity { get; set; }
        public string LowerCalorifer { get; set; }
        public string LsmgoActualConsumptionBoiler1 { get; set; }
        public string LsmgoActualConsumptionBoiler2 { get; set; }
        public string LsmgoActualConsumptionCompositeBoiler { get; set; }
        public string LsmgoActualConsumptionCummins { get; set; }
        public string LsmgoActualConsumptionDg1 { get; set; }
        public string LsmgoActualConsumptionDg2 { get; set; }
        public string LsmgoActualConsumptionDg3 { get; set; }
        public string LsmgoActualConsumptionDg4 { get; set; }
        public string LsmgoActualConsumptionIgg { get; set; }
        public string LsmgoPoolConsumptionBoiler1 { get; set; }
        public string LsmgoPoolConsumptionBoiler2 { get; set; }
        public string LsmgoPoolConsumptionCompositeBoiler { get; set; }
        public string LsmgoPoolConsumptionCummins { get; set; }
        public string LsmgoPoolConsumptionDg1 { get; set; }
        public string LsmgoPoolConsumptionDg2 { get; set; }
        public string LsmgoPoolConsumptionDg3 { get; set; }
        public string LsmgoPoolConsumptionDg4 { get; set; }
        public string LsmgoPoolConsumptionIgg { get; set; }
        public string MeOilOil { get; set; }
        public string MainEngineRevolutionOutputCounter { get; set; }
        public string ObservedWeather { get; set; }
        public string RpmDeclared { get; set; }
        public string RunningHoursBoiler1Lsmgo { get; set; }
        public string RunningHoursBoiler1Vlsfo { get; set; }
        public string RunningHoursBoiler2Lsmgo { get; set; }
        public string RunningHoursBoiler2Vlsfo { get; set; }
        public string RunningHoursCargoCumminsLsmgo { get; set; }
        public string RunningHoursCompositeBoilerLsmgo { get; set; }
        public string RunningHoursCompositeBoilerVlsfo { get; set; }
        public string RunningHoursDg1Lsmgo { get; set; }
        public string RunningHoursDg1Vlsfo { get; set; }
        public string RunningHoursDg2Lsmgo { get; set; }
        public string RunningHoursDg2Vlsfo { get; set; }
        public string RunningHoursDg3Lsmgo { get; set; }
        public string RunningHoursDg3Vlsfo { get; set; }
        public string RunningHoursDg4Lsmgo { get; set; }
        public string RunningHoursDg4Vlsfo { get; set; }
        public string RunningHoursIggLsmgoRunningHours { get; set; }
        public string ScavengeAirInletTemp { get; set; }
        public string ScavengeAirPressure { get; set; }
        public string SeaCurrentSpeed { get; set; }
        public string SeaState { get; set; }
        public string ShaftPowerShapoli { get; set; }
        public string SlipDeclared { get; set; }
        public string Slops { get; set; }
        public string SludgeRob { get; set; }
        public string Sounding { get; set; }
        public string SpeedlogDistance { get; set; }
        public string SulphurContent { get; set; }
        public string SwellDirection { get; set; }
        public string TcAirInletTemp { get; set; }
        public string TankTemperature { get; set; }
        public string TurboChargerRpm { get; set; }
        public string Vcf { get; set; }
        public string VesselCurrentList { get; set; }
        public string VesselCurrentTrim { get; set; }
        public string VlsfoActualConsumptionBoiler1 { get; set; }
        public string VlsfoActualConsumptionBoiler2 { get; set; }
        public string VlsfoActualConsumptionCompositeBoiler { get; set; }
        public string VlsfoActualConsumptionDg1 { get; set; }
        public string VlsfoActualConsumptionDg2 { get; set; }
        public string VlsfoActualConsumptionDg3 { get; set; }
        public string VlsfoActualConsumptionDg4 { get; set; }
        public string VlsfoPoolConsumptionBoiler1 { get; set; }
        public string VlsfoPoolConsumptionBoiler2 { get; set; }
        public string VlsfoPoolConsumptionCompositeBoiler { get; set; }
        public string VlsfoPoolConsumptionDg1 { get; set; }
        public string VlsfoPoolConsumptionDg2 { get; set; }
        public string VlsfoPoolConsumptionDg3 { get; set; }
        public string VlsfoPoolConsumptionDg4 { get; set; }
        public string Volume { get; set; }
        public string Wcf { get; set; }
        public string Weight { get; set; }
        public string WindDirection { get; set; }
        public string WindForce { get; set; }
        public int? Cargo { get; set; }
        public string PortBusinessId { get; set; }
        public double? AverageSpeedThroughTheWater { get; set; }
        public double? AverageSpeedOverGround { get; set; }
        public double? TotalConsumptionEstimated { get; set; }
        public double? TotalConsumptionDeclared { get; set; }
        public double? VlsfoActualConsumptionThroughFlowMetersDiff { get; set; }
        public double? VlsfoPoolConsumptionThroughFlowMetersDiff { get; set; }
        public double? LsmgoActualConsumptionThroughFlowMetersDiff { get; set; }
        public double? LsmgoPoolConsumptionThroughFlowMetersDiff { get; set; }
        public double? MainEngineMaxPower { get; set; }
        public double? PitchPropeller { get; set; }
        public double? TotalDistanceOverGround { get; set; }
        public double? ActualConsVlsfo { get; set; }
        public double? ActualConsLsmgo { get; set; }
        public double? PoolConsVlsfo { get; set; }
        public double? PoolConsLsmgo { get; set; }
        public DateTime? EventTimestampUtc { get; set; }
        public double? Lat { get; set; }
        public double? Long { get; set; }
        public double? BunkeringLsmgo { get; set; }
        public int? IsEu { get; set; }
        public double? RobLfoActual { get; set; }
        public double? RobLfoPool { get; set; }
        public double? BunkeringLfo { get; set; }
        public double? BunkeringHfo { get; set; }
        public string LegId { get; set; }
        public string RobHfoActualTanks { get; set; }
        public string RobHfoPoolTanks { get; set; }
        public string RobMgoActualTanks { get; set; }
        public string RobMgoPoolTanks { get; set; }
        public string PortNameFutureIfOpl { get; set; }
        public string PortBusinessIdFutureIfOpl { get; set; }
        public int? IsEuFutureIfOpl { get; set; }
        public string PortNamePastIfOpl { get; set; }
        public string PortBusinessIdPastIfOpl { get; set; }
        public int? IsEuPastIfOpl { get; set; }
    }

}
